name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install components and build contracts
      run: |
        rustup toolchain install nightly
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
        ./build.sh
    - name: Run tests
      run: cargo test
