[package]
name = "s-token-interface"
authors = ["eq-lab"]
version = "0.1.0"
edition = "2021"
description = "SToken interface"

[dependencies]
soroban-sdk = { workspace = true }

[features]
testutils = ["soroban-sdk/testutils"]
