name: Build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  Build:
    name: Build Soroban Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.79.0
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - name: Install wasm32
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install --locked soroban-cli

      - name: Build & Test soroban Contracts
        run: |
            soroban contract build
