name: Soroban contracts Codecov

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "**"

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Rust
        run: rustup update stable
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install wasm32
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install --locked soroban-cli
      - name: Build & Test soroban Contracts
        run: |
            soroban contract build
      - name: Generate code coverage
        run: 
          cargo llvm-cov --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          flags: rust
          fail_ci_if_error: true