on:
  push:
    branches:
      - main

name: Code coverage check

jobs:

  coverage:
    name: Code Coverage
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust-version: [1.72.0]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}
          target: wasm32-unknown-unknown
          override: true
      - name: Install tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin --version 0.25.2
      - run: make build
      - name: Run code coverage check with tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --workspace --timeout 120 --out Xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cobertura.xml
