[package]
name = "flash-loan-receiver-interface"
authors = ["eq-lab"]
version = "0.1.0"
edition = "2021"
description = "Flash loan receiver interface"

[dependencies]
soroban-sdk = { workspace = true }

[features]
testutils = ["soroban-sdk/testutils"]
